### ISSUE TITLE
Some new NIDs not on your list

### ISSUE THREAD

**Issue by charlyzard** [idc/ps4libdoc#2]
Here you have them (from 4.05 binaries):

libkernel.sprx and libkernel_sys.sprx and libkernel_web.sprx:
nTxZBp8YNG   pthread_mutex_setname_np

libkernel_sys.sprx
yeW8YJ4T7K   sceKernelSuspendSystem

libSceAudioIn.sprx
hWMCAPpqzD   sceAudioInSetSparkSideTone
IQtWgnrw6v   sceAudioInChangeAppModuleState

libSceAudioOut.sprx
Iz9X7ISldh   sceAudioOutA3dControl
MapHTgeogb   sceAudioOutPtClose
n7KgxE8rOu   sceAudioOutA3dInit
O3FM2WXIJa   sceAudioOutChangeAppModuleState
X7Cfsiujm8   sceAudioOutSetUsbVolume
xyT8IUCL3C   sceAudioOutPtOpen
Y3lXfCFEWF   sceAudioOutGetHandleStatusInfo

libSceAvPlayerStreaming.sprx
buBHKGLpYr   sceTsStopFileStreaming
I4Dpeom1P6   sceTsOpenFileEx

libSceAvSetting.sprx
EIZdWTT7Zd   sceAvSettingInit
Ow348nbrI1   sceAvSettingChangeOutputMode
w7ICzzcAJC   sceAvSettingChangeOutputMode2

libSceBgft.sprx
KY6RXUXi6Z   sceBgftServiceDownloadStopTask
ShnEkrw8E8   sceBgftServiceDownloadQueryTask

libSceCamera.sprx
fkZE7Hup2r   sceCameraAudioGetData
LEMk5cTHKE   sceCameraSetCalibData
ztqH5qNTpT   sceCameraCloseByHandle

libSceCompositeExt.sprx
fH2IStnGK4   sceCompositorCommandGpuPerfEnd

libSceFreeTypeOl.sprx and libSceFreeTypeOt.sprx
dH02CpEEcY   FT_Done_FreeType

libSceHidControl.sprx
akmC1nXbrL   sceHidControlGetBatteryState
EfvzrKzujQ   sceHidControlGetDeviceName
u2GrRj85Ri   sceHidControlGetDeviceInfo

libSceHmd.sprx
wHnZU1qtiq   sceHmdInternal3dAudioOpen

libSceImeBackend.sprx
MTHPbVoNR0   sceImeBackendEnterCharacter

libSceMbus.sprx
c08SEHicDN   sceMbusEventCreate_
CwDVsGO6U3   sceMbusAddHandleByUserId
Czjo1Se8pE   sceMbusGetDeviceDescription
eTpWp430DA   sceMbusAcquireControlWithState2
hIAyLXI4V8   sceMbusGetSparkState
LbHgD9w6uA   sceMbusRemoveProxy
Lrelj2uF1L   sceMbusSetScratchData
mP31WHwSVj   sceMbusSetProxy
WNxCIjZdcT   sceMbusDisconnectDevice
WW1zKfNo6H   sceMbusAddHandleByDeviceId

libSceMouse.sprx
ghLUU2Z5Lc   sceMouseSetPointerSpeed

libSceNet.sprx
a6sS6iSE0I   sceNetConfigRoutingShowtCtlVar
toi8xxcSfJ   sceNetConfigRoutingStop

libSceNetCtl.sprx
eCUIlA2t5C   sceNetCtlGetBandwidthInfoIpcInt

libSceNpManager.sprx
cOLn5A3Zoq   sceNpAsmClientGetNpComInfo2
HtpGVrVLOl   sceNpAsmClientGetNpTitleToken
LGEIdgILQe   sceNpManagerPrxStartVsh
rbknaUjpqW   sceNpGetAccountIdA

libSceNpMatching2.sprx
nHZpTF30wt   sceNpMatching2SetExtraInitParam

libScePad.sprx
Oi7FzRWFr0   scePadSwitchConnection
zFJ35q3RVn   scePadShareOutputData

libSceRemoteplay.sprx
ufesWMVX6i   sceRemoteplayGetMbusDeviceInfo

libSceRtc.sprx
BaOKcng8g8   module_start
KpDMrPHvt3   module_stop

libSceSharePlay.sprx
Md7Mdkr8LB   sceSharePlayGetEvent
rWVNHNnEx6   sceSharePlayStartStreaming
zEDkUWLVwF   sceSharePlayStopStandby

libSceSysCore.sprx
os4QwIWwOJ   sceApplicationIsResumable

libSceSystemService.sprx
ec72vt3WEQ   sceSystemServiceChangeCpuClock
GvqPsPX4EU   sceSystemStateMgrTickPartyChat
Z5RgV4Chwx   sceSystemServiceChangeGpuClock

libSceUsbStorage.sprx
Wp8zHTocS5   sceUsbStorageTerm

libSceUserService.sprx
uvVR70ZxFr   sceUserServiceLogin

libSceVideoCoreServerInterface.sprx
h6RcAAgqqT   sceVideoCoreCancelThumbnail
JMNwMECvR4   sceVideoCoreSetThumbnailInfo

libSceVideoOut.sprx
d1AjT2uZJn   sceVideoOutSysGetVblankStatus

libSceVideoRecording.sprx
QNg8KGixrz   sceVideoRecordingCopyBGRAtoNV12

NPXS20113-bdj.elf
RfjBlXjaZe   JVM_RawMonitorCreate
vXlMo2IuqI   JVM_StopThread

**Comment by charlyzard** [comment]
Some more:

A4KPdcTIVu   sceSocialScreenDialogTerminate
A7EKlm22zo   sceLibSecureHashGetBlockSize
aEoi0u2FOi   sceLibSecureCryptographyEncrypt
ajvzc8e2up   sceNpMatching2CreateContextA
AUqJNkobQ1   physhm_unlink
BaOKcng8g8   module_start
BfYmnUyy0e   sceImeBackendClose
bGTjTkHPHT   sceNpTusTryAndSetVariableAAsync
C0gNCiRIi4   sceNpSetGamePresenceOnlineA
CKHlRW2E9d   sceAudio3dPortGetState
co7QF5zVjn   sceImeBackendGetConvertString
CocbHVIKPE   sceNpAuthGetIdTokenA
dDLNFdY8dw   sceNpSignalingCreateContextA
djUtq62Ead   sceLibSecureRandom
eBTreZ84JF   sceAvPlayerSetLogCallback
EYkbvZMNLv   sceImeBackendGetString
F0Sos4cB8Z   sceEditMp4Terminate
fbigNQiZpm   scePlayGoDialogClose
fECamTJKps   scePlayGoDialogInitialize
fIqNvkKIUP   sceLibSecureInit
flPcUaXVXc   sceAudio3dPortGetParameters
Fmx4tapJGz   sceNpTusSetDataAVUserAsync
fXODRwVnRe   sceEditMp4Edit
G420P25pN5   sceCoredumpDebugTriggerCoredump
GB70BZwBCj   sceImeBackendConvertBackward
Gjixv5hqRV   sceNpTusGetMultiUserVariableA
GnG9xqIIEW   sceLibSecureHashResetContext
GpWMCMxa1a   sceLibSecureAddCipher
gQ6cUriNpg   sceNpMatching2JoinRoomA
GWnWQNXZH5   sceNpScoreCreateNpTitleCtxA
GyI2f9yDUX   sceNpMatching2GetUserInfoListA
hK0CCljzJm   sceNpFriendListDialogGetResultA
i4z2NMo9T3   sceLibSecureHashGetDigest
IkL62FMpIp   sceNpInGameMessagePrepareA
iXzUOM9sXU   sceNpTusDeleteMultiSlotDataA
K9tlODTQx3   sceNpScoreGetRankingByAccountId
kbWqOt3QjK   sceNpTusSetDataAVUser
kHd72ukqbx   scePlayGoDialogOpen
KpDMrPHvt3   module_stop
lxNDPDnWfM   sceNpTusGetMultiUserDataStatusA
lyPvxnyBgd   sceLibSecureHashDeleteContext
M3wFXbYQtA   sceNpUnregisterStateCallbackA
MA9vSt7JIm   sceNpScoreGetRankingByRangeA
mJlVV44ycU   sceImeBackendDeleteCharacter
MTHPbVoNR0   sceImeBackendEnterCharacter
n0FeJgonox   sceImeBackendGetConfirmString
NOAMxY2EGS   scePlayGoDialogGetStatus
nrQRlLKzdw   sceNpProfileDialogOpenA
Nt1runsPVJ   sceNpTusAddAndGetVariableAVUser
oGIcxlUabS   sceNpTusTryAndSetVariableAVUser
okgIGdr5Iz   scePlayGoDialogTerminate
oPO9U42Ypg   sceNpGetGamePresenceStatusA
OVNpYTRqN7   sceSocialScreenTerminate
P5slpXsXy0   sceLibSecureRemoveHash
PEe0R7gBHb   sceSocialScreenDialogInitialize
pGllkf3ECv   sceLibSecureHashAddMessage
PI7jIZj4pc   sceRandomGetRandomNumber
pI7oFSPP65   sceSocialScreenInitialize
PQDFxcnqxt   sceNpInGameMessageSendDataA
pu4kxXkYz3   sceVideodec2CreateHevcDecoder
q3M7XzBKC3   sceNpGetAccountDateOfBirthA
qAUXQ9GdWp   sceNpAuthGetAuthorizationCodeA
QHFJB2F0p3   sceGameCustomDataDialogOpenA
qQJfO8HAia   sceNpRegisterStateCallbackA
rbknaUjpqW   sceNpGetAccountIdA
rMyh97BU5p   sceNetGetMemoryPoolStats
rWapdQmQQR   sceEditMp4Abort
sAxbHhAWMX   sceInvitationDialogOpenA
SEggctIeTc   sceAudio3dPortGetList
Shr7bZq8QH   sceNpSignalingGetPeerNetInfoA
SvdXHHt2LL   sceSocialScreenOpenSeparateMode
TaNw7W25QJ   sceNpPartyGetMembersA
TPMbgIxvog   sceNpGetAccountLanguageA
TzoWJFBjBW   sceEditMp4Initialize
uJ0VhGcxCT   sceAudio3dPortFreeState
uoFvgzwawA   sceNpTusGetDataAVUserAsync
v2RYVGrJDk   sceNpPartyGetMemberInfoA
V6KSpKv9XJ   sceNpMatching2CreateJoinRoomA
VgYczPGB5s   sceNpGetUserIdByAccountId
vN9sTP63WT   sceNpFriendListDialogOpenA
VzxN3tOouj   sceNpTusSetDataA
W5iJUafU8r   sceEditMp4GetStatus
WjHT5TmV0T   sceSocialScreenDialogGetResult
WuuUhuKOxw   sceInvitationDialogGetResultA
WVBXdDlF1T   sceEditMp4InitializeParam
wx9TDplJKB   scePlayGoDialogGetResult
XQSUbbnpPB   sceNpPartyCreateA
Xva83fZZ7D   sceImeBackendGetCaretIndex
xzG8mG9YlK   sceNpTusGetDataAAsync
yARHEYLajs   sceNpPartyShowInvitationListA
Yb60K7BST4   scePlayGoDialogUpdateStatus
YGvqDPyza1   sceLibSecureHashGetDigestSize
yixh7HDKWf   sceNpTusGetFriendsDataStatusA
yN7Jhuv8g2   sceAvPlayerVprintf
yWEHUFkY1q   sceNpTusGetDataA
zk6c65xoyO   sceNpWebApiCreateContextA

**Comment by idc** [comment]
You don't need to include the name of the module or the encoded ID.

Thanks.
